---
- name: Ensure Docker directory exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure Docker daemon
  ansible.builtin.copy:
    src: daemon_common.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
