---

- name: Initialize Docker Swarm on Manager nodes
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ ansible_host }}"
  when: is_manager

- name: Get Worker Join Token on Manager node
  ansible.builtin.command: docker swarm join-token -q worker
  register: worker_token
  changed_when: false
  when: is_manager

- name: Get Manager Join Token on Manager node
  ansible.builtin.command: docker swarm join-token -q manager
  register: manager_token
  changed_when: false
  when: is_manager

- name: Store Join Tokens on Manager node
  ansible.builtin.set_fact:
    swarm_worker_token: "{{ worker_token.stdout }}"
    swarm_manager_token: "{{ manager_token.stdout }}"
  when: is_manager
