name: MiniPaaS CI

on:
  pull_request:
  push:
    paths:
      - 'minipaas-cli/**'
      - 'minipaas-role/**'
      - 'docs/**'
      - 'mk/**'
      - 'Makefile'
      - '.github/workflows/**'
    branches:
      - main
  workflow_dispatch:

env:
  GO_VERSION: '1.25'
  HUGO_VERSION: '0.154.3'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: minipaas-cli/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.13
          working-directory: minipaas-cli

      - name: Check import rules
        run: make imports
        working-directory: minipaas-cli

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: minipaas-cli/go.sum

      - name: Install dependencies
        run: go mod tidy
        working-directory: minipaas-cli

      - name: Run Go tests
        run: make test
        working-directory: minipaas-cli

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: docs/go.sum

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Build docs
        run: make build-docs
