name: MiniPaaS Release

on:
  push:
    tags:
      - "*.*.*"

env:
  GO_VERSION: '1.25'
  HUGO_VERSION: '0.154.3'

jobs:

  build-role:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build Ansible Role Tarball
        run: |
          cd minipaas-role
          tar -czf ../minipaas-role.tar.gz *

      - name: Upload Ansible Role Artifact
        uses: actions/upload-artifact@v4
        with:
          name: minipaas-role
          path: minipaas-role.tar.gz

  build-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
        include:
          - goos: darwin
            os: macos-latest
          - goos: linux
            os: ubuntu-latest
          - goos: windows
            os: windows-latest
            suffix: .exe
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: minipaas-cli/go.sum

      - name: Install dependencies
        run: go mod tidy
        working-directory: minipaas-cli

      - name: Build CLI
        run: make -C minipaas-cli build WHAT=minipaas

      - name: List files
        run: ls -la minipaas-cli

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: minipaas-${{ matrix.goos }}-${{ matrix.goarch }}
          path: minipaas-cli/build/minipaas*

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: docs/go.sum

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Build docs
        run: make build-docs

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/public

  release:
    runs-on: ubuntu-latest
    needs: [build-cli, build-role, build-docs]
    permissions:
      contents: write
    steps:
      - name: Download CLI artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-artifacts
          pattern: minipaas-*
          merge-multiple: true

      - name: Download Ansible Role Artifacts
        uses: actions/download-artifact@v4
        with:
          name: minipaas-role
          path: ./release-artifacts

      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-artifacts/*

  docs:
    runs-on: ubuntu-latest
    needs: [ release ]
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
